# Generated by Django 3.2.16 on 2023-04-26 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='isin',
            field=models.CharField(default=0, max_length=12),
            preserve_default=False,
        ),
    ]
