# Generated by Django 3.2.16 on 2023-04-29 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_share_isin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='ticker',
            field=models.CharField(max_length=35),
        ),
    ]
