# Generated by Django 3.2.16 on 2023-05-08 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_alter_share_ticker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='isin',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='share',
            name='ticker',
            field=models.CharField(max_length=40),
        ),
    ]
